{% set name = "reverse-argparse" %}
{% set version = "2.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: 1140064b00d6e5abad698e5d1673fe1541a023f22ffb0546e226b0814dd8f76f
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reverse_argparse-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
  imports:
    - reverse_argparse
  requires:
    - pip
    - python {{ python_min }}

about:
  description: |
    Whereas argparse is concerned with taking a bunch of command line arguments
    and parsing them, this package is intended to do the opposite; that is,
    it'll take the parsed arguments and create the effective command line
    invocation of the script that generated them.  The motivation is to be able
    to tell users exactly what was used for all of the options, taking into
    consideration any defaults and other transformations that might've been
    applied in the midst of parsing, such that users are able to reproduce a
    prior run of a script exactly.
  dev_url: https://github.com/sandialabs/reverse_argparse
  doc_url: https://reverse-argparse.readthedocs.io
  home: https://github.com/sandialabs/reverse_argparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Generate the effective command line invocation for a script.

extra:
  recipe-maintainers:
    - jmgate
